export const ADD_SCREENING = "ADD_SCREENING";
export const UPDATE_SCREENING = "UPDATE_SCREENING";
export const UPDATE_SCREENINGS = "UPDATE_SCREENINGS";

export const ADD_LOCATION = "ADD_LOCATION";
export const LOGIN = "LOGIN";

export const UPDATE_REFRESH_STATUS = "UPDATE_REFRESH_STATUS"
